### ISSUE TITLE
Instrument system For files

### ISSUE THREAD

**Issue by DrLynch** [ArgLab/ArgLab_writing_observer#106]
Our primary issue right now is that we have files not being closed.  As part of the fix we need to develop a clearer model of how long the files are open relative to the actions within them.  The files have no "heartbeat" actions but a system close time may be sufficient.  

One sufficient approach would be to detect close events and add them to the log to track closing processes or to track a last write.

**Comment by Brendon-Hablutzel** [comment]
## Status Update

Each time the server receives a new websocket connection, it opens two log files for writing events to

However, after some amount of time without user input in the google doc, the websocket connection is closed (unsure by which end) and the server stops using the log files it created--however, there is no call in python to `close()` and `lsof` shows that the files are still open.

Then, when the user reconnects by performing an action in the doc, the server creates new log files and uses those for new events, without closing the previous files.

**Comment by Brendon-Hablutzel** [comment]
# Status Update

Progress on a fix for this issue is being worked on in [my fork](https://github.com/Brendon-Hablutzel/writing_observer/tree/master) of the ETS repository because the ETS repository contains overhauled `incoming_student_event.py` code.

**Comment by Brendon-Hablutzel** [comment]
This was fixed directly on the ETS repo with [this pull request](https://github.com/ETS-Next-Gen/writing_observer/pull/126)
